### ISSUE TITLE
Setup Stripe in C# Lambda Function

### ISSUE THREAD

**Issue by lukejoshuapark** [Boys-In-The-Shed/PiggyBank#7]
See Step 1 of https://stripe.com/docs/payments/accept-a-payment?platform=web&ui=elements

Create a new class library project `PiggyBank.Stripe` and install the following package (commands below):

```
mkdir PiggyBank.Stripe
dotnet new classlib
dotnet add package Stripe.net
cd ..
dotnet sln add PiggyBank.Stripe
```

**Comment by Prashant-Naicker** [comment]
I want to `cd PiggyBank.Stripe` after `mkdir` and before the `dotnet` command?

**Comment by lukejoshuapark** [comment]
> 
> 
> I want to `cd PiggyBank.Stripe` after `mkdir` and before the `dotnet` command?

Correct! `dotnet new` creates a new project inside the current directory.

**Comment by Prashant-Naicker** [comment]
How do I create a `sln` file? I thought creating the project would prompt it or something?

Here you can see my folder structure and the error I get when I run `dotnet sln add PiggyBank.Stripe`:
![image](https://user-images.githubusercontent.com/16055242/130544592-1605f0a3-2b6c-427e-b3b6-5aa446d1087b.png)

**Comment by lukejoshuapark** [comment]
Ahh sorry all of the above needs to start inside the `./src/PiggyBank` folder - you started inside `./src`

**Comment by Prashant-Naicker** [comment]
Sweet! Cheers
